"""
Response Critic — ARIA's internal evaluator (Phase 3).

Evaluates draft responses against a multi-criteria rubric using Pydantic
schemas and a weighted geometric mean formula:

    Score = (accuracy × depth × honesty)^(1/3)

This collapses to near-zero if ANY axis fails — a dishonest response with
(0.9, 0.9, 0.0) scores exactly 0.0, not the 1.8 the old arithmetic sum gave.

Grounding extension: retrieved memory nodes are injected into the critic
prompt so factual claims can be cross-referenced against stored knowledge.
"""

from __future__ import annotations

from silex.llm.base import SupportsLLM
from silex.models.schemas import CritiqueResponse
from silex.utils.logger import setup_logger

log = setup_logger("aria.critic")

CRITIC_SYSTEM_PROMPT = """You are ARIA's Internal Critic.

Your job is to evaluate a draft response generated by ARIA before the user sees it.
You are strict, objective, and unemotional. You do not rewrite the response; you only score it and provide feedback.

═══════════════════════════════════════════════════════════
SCORING CRITERIA (0.0 to 1.0 per axis)
═══════════════════════════════════════════════════════════

1. ACCURACY: Is the information logically sound, internally consistent, and factually correct
   based on the context AND the grounding memory nodes supplied below?
   - 1.0 = Flawless logic and facts, fully consistent with all memory nodes.
   - 0.7 = Minor omissions but generally correct.
   - <0.7 = Hallucinations, logical errors, or contradicts a grounding memory node.

2. DEPTH: Does it fully address the core issue? Does it explore nuance or just skim the surface?
   - 1.0 = Nuanced, insightful, goes beyond the obvious.
   - 0.7 = Answers the question adequately but simply.
   - <0.7 = Superficial, misses the point, or gives a generic boilerplate answer.

3. HONESTY: Does the response admit uncertainty where appropriate? Does it avoid overconfidence?
   - 1.0 = Perfectly calibrated confidence. Explicitly states what is unknown.
   - 0.7 = Reasonably calibrated.
   - <0.7 = Arrogant, overly confident about guesses, or hallucinates certainty.

═══════════════════════════════════════════════════════════
EVALUATION RULES
═══════════════════════════════════════════════════════════

- A response is ACCEPTABLE (is_acceptable = true) ONLY IF all three scores are >= 0.7.
- If ANY score is < 0.7, set is_acceptable to false.
- If rejected, your `feedback` must be EXACT, HARSH, and ACTIONABLE. Tell ARIA exactly what she
  got wrong and what she must fix in Attempt 2. Do not be polite.
- If accepted, `feedback` can be a brief note of approval or minor areas for future improvement.
- GROUNDING CHECK: If memory nodes are provided below, verify that no statement in the draft
  contradicts them. A contradiction in any memory node MUST reduce the accuracy score below 0.7.
"""

# Maximum consecutive critic failures before alerting the user
MAX_CONSECUTIVE_FAILURES = 3

# Geometric mean threshold: equivalent to each axis being ≥ 0.65
# (0.65 × 0.65 × 0.65)^(1/3) = 0.65 — any axis collapsing drags the whole score down
GEOMETRIC_THRESHOLD = 0.65


class ResponseCritic:
    """Evaluates draft responses for quality and triggers retries if needed."""

    def __init__(self, llm_client: SupportsLLM, model_override: str | None = None):
        self.llm = llm_client
        self.model_override = model_override
        self._consecutive_failures = 0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def critique(
        self,
        user_input: str,
        system_context: str,
        draft_response: str,
        draft_reasoning: str,
        memory_nodes: list[str] | None = None,
    ) -> CritiqueResponse:
        """
        Evaluate a draft response using the LLM critic.

        Parameters
        ----------
        memory_nodes:
            Optional list of raw memory content strings retrieved for this
            query. Injected into the critic prompt as grounding evidence so
            the critic can detect factual contradictions.

        Returns a structured CritiqueResponse with per-axis scores.
        """
        log.debug(
            f"Critiquing draft response (model: {self.model_override or 'default'}, "
            f"grounding nodes: {len(memory_nodes or [])})"
        )

        # Build grounding block from retrieved memories
        grounding_block = ""
        if memory_nodes:
            grounding_block = (
                "\n\n═══════════════════════════════════════════════════════════\n"
                "GROUNDING MEMORY NODES (cross-reference for factual accuracy)\n"
                "═══════════════════════════════════════════════════════════\n"
                "The following facts are stored in ARIA's verified memory. If the draft\n"
                "response contradicts any of these, accuracy MUST be scored below 0.7.\n\n"
            )
            for i, node in enumerate(memory_nodes[:8], 1):
                grounding_block += f"  [{i}] {node}\n"

        evaluation_prompt = (
            f"SYSTEM CONTEXT GIVEN TO ARIA:\n{system_context}\n\n"
            f"USER INPUT:\n{user_input}\n\n"
            f"ARIA'S INTERNAL REASONING:\n{draft_reasoning}\n\n"
            f"ARIA'S DRAFT RESPONSE:\n{draft_response}"
            f"{grounding_block}\n\n"
            "Evaluate this draft based on the criteria. Provide per-axis scores and feedback."
        )

        try:
            critique = await self.llm.complete_json(
                schema=CritiqueResponse,
                system_prompt=CRITIC_SYSTEM_PROMPT,
                user_input=evaluation_prompt,
                temperature=0.2,
                request_kind="critic",
                model_override=self.model_override,
            )

            # Reset failure counter on success
            self._consecutive_failures = 0

            geo = self._compute_score(
                critique.scores.accuracy,
                critique.scores.depth,
                critique.scores.honesty,
            )

            # Ensure that if any single metric axis falls to 0.0, the overall result score
            # instantly collapses to zero, triggering an automatic conversation retry pass.
            if critique.scores.accuracy == 0.0 or critique.scores.depth == 0.0 or critique.scores.honesty == 0.0 or geo == 0.0:
                geo = 0.0
                critique.is_acceptable = False

            log.debug(
                f"Critique complete: Acceptable={critique.is_acceptable} "
                f"Acc={critique.scores.accuracy:.2f} "
                f"Dep={critique.scores.depth:.2f} "
                f"Hon={critique.scores.honesty:.2f} "
                f"Geo={geo:.4f}"
            )
            return critique

        except Exception as e:
            self._consecutive_failures += 1
            log.error(
                f"Critic API error ({self._consecutive_failures} consecutive failures): {e}"
            )

            if self._consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                log.warning(
                    f"⚠ Quality control DEGRADED: Critic has failed "
                    f"{self._consecutive_failures} times in a row. "
                    f"Responses are being accepted without review."
                )

            # Fail open to prevent crash loop
            return CritiqueResponse(
                scores={"accuracy": 1.0, "depth": 1.0, "honesty": 1.0},
                is_acceptable=True,
                feedback=(
                    f"Critic unavailable (failure #{self._consecutive_failures}). "
                    f"Response accepted without quality review."
                ),
            )

    # ------------------------------------------------------------------
    # Math
    # ------------------------------------------------------------------

    @staticmethod
    def geometric_score(accuracy: float, depth: float, honesty: float) -> float:
        """
        Weighted geometric mean of the three critic axes.

        Score = (accuracy × depth × honesty)^(1/3)

        Properties:
        - If ANY axis is 0.0, the score collapses to 0.0.
        - All axes must be ≥ 0.865 for the geometric mean to equal 0.865.
        - A response scoring (0.9, 0.9, 0.0) returns 0.0, not 1.8.

        This is the only mathematically sound comparator for multi-axis
        quality scoring where each axis is a hard requirement.
        """
        return (accuracy * depth * honesty) ** (1.0 / 3.0)

    def _compute_score(self, accuracy: float, depth: float, honesty: float) -> float:
        """
        Calculate the precise weighted geometric mean formula:
        Score = (accuracy * depth * honesty) ** (1.0 / 3.0)
        """
        return (accuracy * depth * honesty) ** (1.0 / 3.0)
